name: gc-website-${STACK_ENV:-local}
services:
  gc-website-nginx:
    container_name: gc-website-${STACK_ENV:-local}-nginx
    image: 'gc/nginx:${STACK_VERSION:-latest}'
    restart: unless-stopped
    network_mode: bridge
    env_file: stack.env
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - NGINX_PORT=${NGINX_PORT:-80}
    labels:
      logging: promtail
      logging_jobname: gc-website-nginx
    ports:
      - ${NGINX_HOST_PORT:-8080}:80
    links:
      - 'gc-website-next:next-app'
    depends_on:
      - gc-website-next
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  gc-website-next:
    container_name: gc-website-${STACK_ENV:-local}-next
    image: 'gc/next:${STACK_VERSION:-latest}'
    restart: unless-stopped
    network_mode: bridge
    env_file: stack.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    labels:
      logging: promtail
      logging_jobname: gc-website-next
    ports:
      - ${APP_HOST_PORT}:3000
    healthcheck:
      test: curl --fail http://localhost:3000/api/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
