name: gcirone-site
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache
  NEXT_TELEMETRY_DISABLED: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Install dependencies
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn cypress install && yarn cypress verify

      - name: Build application
        run: |
          yarn site:lint
          yarn site:export

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: gcirone-site
          path: dist/apps/gcirone-site/exported

  tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-scripts: [ test, e2e ]

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Run script ${{ matrix.node-scripts }}
        run: yarn site:${{ matrix.node-scripts }}

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: gcirone-site
          path: dist/apps/gcirone-site/exported

      - name: Publish github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/apps/gcirone-site/exported
