name: gcirone-site
on:
  push:
    branches: [ next-update ]
  pull_request:
    branches: [ next-update ]
  workflow_dispatch:

env:
  CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache
  NODE_ENV: production

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Install dependencies
        if: steps.modules-cache.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile
          yarn cypress install && yarn cypress verify

      - name: Build application
        run: |
          yarn site:export

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: gcirone-site
          path: dist/apps/gcirone-site/exported

  tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-scripts: [ test, e2e ]

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Modules cache
        uses: actions/cache@v3
        id: modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-modules-

      - name: Run script ${{ matrix.node-scripts }}
        run: yarn site:${{ matrix.node-scripts }}

#  deploy:
#    needs: tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout changes
#        uses: actions/checkout@v2
#
#      - name: Download artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: gcirone-site
#          path: dist/site/browser
#
#      - name: Publish github pages
#        uses: JamesIves/github-pages-deploy-action@4.1.0
#        with:
#          branch: gh-pages
#          folder: dist/site/browser
